[build]
  command = "npm run build:client"
  publish = "dist/spa"

# Build environment
[build.environment]
  ROLLUP_SKIP_NATIVE = "true"
  NODE_VERSION = "22.19.0"

# Optional: single-page app routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
